module.exports = {
  JOIN_ROOM:     'join-room',
  LEAVE_ROOM:    'leave-room',
  DRAW:          'draw',
  CURSOR:        'cursor',
  CLEAR:         'clear',
  SHAPE:         'shape',
  AI_DIAGRAM:    'ai-diagram',
  FLOWCHART:     'flowchart',
  SUMMARY:       'summary',
  USER_JOINED:   'user-joined',
  USER_LEFT:     'user-left',
  ROOM_USERS:    'room-users',
  ERROR:         'error',
  // Object system
  OBJECT_ADD:    'object-add',
  OBJECT_DELETE: 'object-delete',
  OBJECT_UPDATE: 'object-update',
  UNDO:          'undo',
  REDO:          'redo',
  CANVAS_STATE:  'canvas-state',
};
